package Daje::Database::View::Super::vCompaniesDefaults;
use Mojo::Base 'Daje::Database::Model::Super::Common::Base', -base, -signatures, -async_await;
use v5.42;

# NAME
# ====
#
# Daje::Database::View::Super::vCompaniesDefaults - Daje db model
#
# SYNOPSIS
# ========
#
#
#       use Daje::Database::View::Super::vCompaniesDefaults;
#
#       my $table = Daje::Database::View::Super::vCompaniesDefaults->new(db => $db);
#
#       my $result = $table->load_companies_defaults_pkey($self, $companies_defaults_pkey);
##
#
#
# DESCRIPTION
# ===========
#
# Daje::Database::View::Super::vCompaniesDefaults is a View super class
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated automatically by Daje Tools 2026-04-06 14:13:00.
# It will be re-created by Daje Tools again and any changes
# will be over written.
#
# <!-- Autogenerated file 2026-04-06 14:13:00 -->

our $VERSION = '0.01';

has 'fields' => '"companies_defaults_pkey", "editnum", "insby", "insdatetime", "modby", "moddatetime","key","value","category"';
has 'primary_key_name' => "companies_defaults_pkey";
has 'table_name' => "v_companies_defaults";


async sub load_companies_defaults_pkey_p($self, $companies_pkey, $users_pkey, $companies_defaults_pkey) {
    return $self->load_companies_defaults_pkey($companies_pkey, $users_pkey, $companies_defaults_pkey);
}

sub load_companies_defaults_pkey($self, $companies_pkey, $users_pkey, $companies_defaults_pkey) {
    return $self->load_pk(
        $self->table_name, $self->fields(), $self->primary_key_name(), $companies_defaults_pkey
    );
}

1;

