package Daje::Database::View::Super::vCompaniesCompaniesList;
use Mojo::Base 'Daje::Database::Model::Super::Common::Base', -base, -signatures, -async_await;
use v5.42;

# NAME
# ====
#
# Daje::Database::View::Super::vCompaniesCompaniesList - Daje db view
#
# SYNOPSIS
# ========
#
#
#       use Daje::Database::View::Super::vCompaniesCompaniesList;
#
#       my $table = Daje::Database::View::Super::vCompaniesCompaniesList->new(db => $db);
#
#       my $result = $table->load_companies_companies_pkey($self, $companies_companies_pkey);
##
#       my $result = $table->insert($self, $data);
#
#       $table->update($self, $data) ;
#
#
# DESCRIPTION
# ===========
#
# Daje::Database::View::Super::CompaniesCompaniesList is a Model super class
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated automatically by Daje Tools 2026-02-01 16:22:08.
# It will be re-created by Daje Tools again and any changes
# will be over written.
#
# <!-- Autogenerated file 2026-02-01 16:22:08 -->

our $VERSION = '0.01';

has 'fields' => '"companies_companies_pkey", "editnum", "insby", "insdatetime", "modby", "moddatetime","name","registrationnumber","homepage"';
has 'primary_key_name' => "companies_companies_pkey";
has 'table_name' => "v_companies_companies_list";

async sub load_all_companies_companies_p($self) {
    return $self->load_all_companies_companies();
}

sub load_all_companies_companies($self) {
    return $self->load_a_full_list(
        $self->table_name, $self->fields()
    );
}
1;


