package Daje::Database::View::Super::vCompaniesDefaultsList;
use Mojo::Base 'Daje::Database::Model::Super::Common::Base', -base, -signatures, -async_await;
use v5.42;

# NAME
# ====
#
# Daje::Database::View::Super::vCompaniesDefaultsList - Daje db view
#
# SYNOPSIS
# ========
#
#
#       use Daje::Database::View::Super::vCompaniesDefaultsList;
#
#       my $table = Daje::Database::View::Super::vCompaniesDefaultsList->new(db => $db);
#
#       my $result = $table->load_companies_defaults_pkey($self, $companies_defaults_pkey);
##
#       my $result = $table->insert($self, $data);
#
#       $table->update($self, $data) ;
#
#
# DESCRIPTION
# ===========
#
# Daje::Database::View::Super::CompaniesDefaultsList is a Model super class
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated automatically by Daje Tools 2026-04-06 14:13:00.
# It will be re-created by Daje Tools again and any changes
# will be over written.
#
# <!-- Autogenerated file 2026-04-06 14:13:00 -->

our $VERSION = '0.01';

has 'fields' => '"companies_defaults_pkey", "editnum", "insby", "insdatetime", "modby", "moddatetime","key","value","category"';
has 'primary_key_name' => "companies_defaults_pkey";
has 'table_name' => "v_companies_defaults_list";

async sub load_all_companies_defaults_p($self, $companies_pkey, $users_pkey) {
    return $self->load_all_companies_defaults($companies_pkey, $users_pkey);
}

sub load_all_companies_defaults($self, $companies_pkey, $users_pkey) {    return $self->load_a_full_list(
        $self->table_name, $self->fields()
    );}
1;


