package Daje::Database::View::Super::vCompaniesRoles;
use Mojo::Base 'Daje::Database::Model::Super::Common::Base', -base, -signatures, -async_await;
use v5.42;

# NAME
# ====
#
# Daje::Database::View::Super::vCompaniesRoles - Daje db model
#
# SYNOPSIS
# ========
#
#
#       use Daje::Database::View::Super::vCompaniesRoles;
#
#       my $table = Daje::Database::View::Super::vCompaniesRoles->new(db => $db);
#
#       my $result = $table->load_companies_roles_pkey($self, $companies_roles_pkey);
#
#       my $result = $table->load_companies_companies_fkey($self, $companies_companies_fkey);
#
#       my $result = $table->load_companies_role_fkey($self, $companies_role_fkey);
##
#
#
# DESCRIPTION
# ===========
#
# Daje::Database::View::Super::vCompaniesRoles is a View super class
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated automatically by Daje Tools 2026-02-13 14:55:23.
# It will be re-created by Daje Tools again and any changes
# will be over written.
#
# <!-- Autogenerated file 2026-02-13 14:55:23 -->

our $VERSION = '0.01';

has 'fields' => '"companies_roles_pkey", "editnum", "insby", "insdatetime", "modby", "moddatetime","companies_companies_fkey","description","authorities_role_fkey"';
has 'primary_key_name' => "companies_roles_pkey";
has 'table_name' => "v_companies_roles";


async sub load_companies_companies_fkey_p($self, $companies_companies_fkey) {
    return $self->load_companies_companies_fkey($companies_companies_fkey);
}

sub load_companies_companies_fkey($self, $companies_companies_fkey) {
    return $self->load_fkey(
        $self->table_name, $self->fields(), "companies_companies_fkey", $companies_companies_fkey
    );
}
async sub load_authorities_role_fkey_p($self, $authorities_role_fkey) {
    return $self->load_authorities_role_fkey($authorities_role_fkey);
}

sub load_authorities_role_fkey($self, $authorities_role_fkey) {
    return $self->load_fkey(
        $self->table_name, $self->fields(), "authorities_role_fkey", $authorities_role_fkey
    );
}
async sub load_companies_roles_pkey_p($self, $companies_roles_pkey) {
    return $self->load_companies_roles_pkey($companies_roles_pkey);
}

sub load_companies_roles_pkey($self, $companies_roles_pkey) {
    return $self->load_pk(
        $self->table_name, $self->fields(), $self->primary_key_name(), $companies_roles_pkey
    );
}

1;

