package Daje::Database::View::Super::vCompaniesCompaniesList;
use Mojo::Base 'Daje::Database::Model::Super::Common::Base', -base, -signatures, -async_await;
use v5.42;

# NAME
# ====
#
# Daje::Database::View::Super::vCompaniesCompaniesList - Daje db view
#
# SYNOPSIS
# ========
#
#
#       use Daje::Database::View::Super::vCompaniesCompaniesList;
#
#       my $table = Daje::Database::View::Super::vCompaniesCompaniesList->new(db => $db);
#
#       my $result = $table->load_companies_companies_pkey($self, $companies_companies_pkey);
#
#       my $result = $table->load_companies_workflow_fkey($self, $companies_workflow_fkey);
#
#       my $result = $table->load_companies_lan_fkey($self, $companies_lan_fkey);
##
#       my $result = $table->insert($self, $data);
#
#       $table->update($self, $data) ;
#
#
# DESCRIPTION
# ===========
#
# Daje::Database::View::Super::CompaniesCompaniesList is a Model super class
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated automatically by Daje Tools 2026-04-04 13:30:53.
# It will be re-created by Daje Tools again and any changes
# will be over written.
#
# <!-- Autogenerated file 2026-04-04 13:30:53 -->

our $VERSION = '0.01';

has 'fields' => '"companies_companies_pkey", "editnum", "insby", "insdatetime", "modby", "moddatetime","registrationnumber","homepage","active","boards_office","companies_workflow_fkey","name",languages_lan_iso_code,
"languages_lan_fkey"';
has 'primary_key_name' => "companies_companies_pkey";
has 'table_name' => "v_companies_companies_list";

async sub load_all_companies_workflow_list_p($self, $companies_pkey, $users_pkey) {
    return $self->load_all_companies_workflow_list($companies_pkey, $users_pkey);
}

sub load_all_companies_workflow_list($self, $companies_pkey, $users_pkey) {
    return $self->load_a_full_list(
        $self->table_name, $self->fields()
    );
}

async sub load_companies_workflow_list_p($self, $companies_pkey, $users_pkey, $key_value) {
    return $self->load_companies_workflow_list($companies_pkey, $users_pkey, $key_value);
}

sub load_companies_workflow_list($self, $companies_pkey, $users_pkey, $key_value) {
    return $self->load_a_list(
        $self->table_name, $self->fields(), $key_value
    );
}
async sub load_all_languages_lan_list_p($self, $companies_pkey, $users_pkey) {
    return $self->load_all_languages_lan_list($companies_pkey, $users_pkey);
}

sub load_all_languages_lan_list($self, $companies_pkey, $users_pkey) {
    return $self->load_a_full_list(
        $self->table_name, $self->fields()
    );
}

async sub load_languages_lan_list_p($self, $companies_pkey, $users_pkey, $key_value) {
    return $self->load_companies_lan_list($companies_pkey, $users_pkey,$key_value);
}

sub load_languages_lan_list($self, $companies_pkey, $users_pkey, $key_value) {
    return $self->load_a_list(
        $self->table_name, $self->fields(), $key_value
    );
}
async sub load_all_companies_companies_p($self, $companies_pkey, $users_pkey) {
    return $self->load_all_companies_companies($companies_pkey, $users_pkey);
}

sub load_all_companies_companies($self, $companies_pkey, $users_pkey) {
    return $self->load_a_full_list(
        $self->table_name, $self->fields()
    );
}
1;


