package Daje::Database::View::Super::vCompaniesPositionsList;
use Mojo::Base 'Daje::Database::Model::Super::Common::Base', -base, -signatures, -async_await;
use v5.42;

# NAME
# ====
#
# Daje::Database::View::Super::vCompaniesPositionsList - Daje db view
#
# SYNOPSIS
# ========
#
#
#       use Daje::Database::View::Super::vCompaniesPositionsList;
#
#       my $table = Daje::Database::View::Super::vCompaniesPositionsList->new(db => $db);
#
#       my $result = $table->load_companies_positions_pkey($self, $companies_positions_pkey);
#
#       my $result = $table->load_companies_companies_fkey($self, $companies_companies_fkey);
##
#       my $result = $table->insert($self, $data);
#
#       $table->update($self, $data) ;
#
#
# DESCRIPTION
# ===========
#
# Daje::Database::View::Super::CompaniesPositionsList is a Model super class
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated automatically by Daje Tools 2026-04-06 14:13:00.
# It will be re-created by Daje Tools again and any changes
# will be over written.
#
# <!-- Autogenerated file 2026-04-06 14:13:00 -->

our $VERSION = '0.01';

has 'fields' => '"companies_positions_pkey", "editnum", "insby", "insdatetime", "modby", "moddatetime","position","companies_companies_fkey"';
has 'primary_key_name' => "companies_positions_pkey";
has 'table_name' => "v_companies_positions_list";

async sub load_all_companies_companies_list_p($self, $companies_pkey, $users_pkey) {
    return $self->load_all_companies_companies_list($companies_pkey, $users_pkey);
}

sub load_all_companies_companies_list($self, $companies_pkey, $users_pkey) {
    return $self->load_a_list(
        $self->table_name, $self->fields(), { companies_companies_fkey => $companies_pkey }
    );
}

async sub load_companies_companies_list_p($self, $companies_pkey, $users_pkey, $key_value) {
    return $self->load_companies_companies_list($companies_pkey, $users_pkey, $key_value);
}

sub load_companies_companies_list($self, $companies_pkey, $users_pkey, $key_value) {
    return $self->load_a_list(
        $self->table_name, $self->fields(), $key_value
    );
}
async sub load_all_companies_positions_p($self, $companies_pkey, $users_pkey) {
    return $self->load_all_companies_positions($companies_pkey, $users_pkey);
}

sub load_all_companies_positions($self, $companies_pkey, $users_pkey) {    return $self->load_a_list(
        $self->table_name, $self->fields(), { companies_companies_fkey => $companies_pkey }
    );}
1;


