package Daje::Database::View::Super::vCompaniesDepartments;
use Mojo::Base 'Daje::Database::Model::Super::Common::Base', -base, -signatures, -async_await;
use v5.42;

# NAME
# ====
#
# Daje::Database::View::Super::vCompaniesDepartments - Daje db model
#
# SYNOPSIS
# ========
#
#
#       use Daje::Database::View::Super::vCompaniesDepartments;
#
#       my $table = Daje::Database::View::Super::vCompaniesDepartments->new(db => $db);
#
#       my $result = $table->load_companies_departments_pkey($self, $companies_departments_pkey);
#
#       my $result = $table->load_companies_companies_fkey($self, $companies_companies_fkey);
##
#
#
# DESCRIPTION
# ===========
#
# Daje::Database::View::Super::vCompaniesDepartments is a View super class
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated automatically by Daje Tools 2026-04-04 13:30:53.
# It will be re-created by Daje Tools again and any changes
# will be over written.
#
# <!-- Autogenerated file 2026-04-04 13:30:53 -->

our $VERSION = '0.01';

has 'fields' => '"companies_departments_pkey", "editnum", "insby", "insdatetime", "modby", "moddatetime","companies_companies_fkey","department"';
has 'primary_key_name' => "companies_departments_pkey";
has 'table_name' => "v_companies_departments";


async sub load_companies_companies_fkey_p($self, $companies_pkey, $users_pkey, $companies_companies_fkey) {
    return $self->load_companies_companies_fkey($companies_pkey, $users_pkey, $companies_companies_fkey);
}

sub load_companies_companies_fkey($self, $companies_pkey, $users_pkey, $companies_companies_fkey) {
    return $self->load_fkey(
        $self->table_name, $self->fields(), "companies_companies_fkey", $companies_companies_fkey
    );
}
async sub load_companies_departments_pkey_p($self, $companies_pkey, $users_pkey, $companies_departments_pkey) {
    return $self->load_companies_departments_pkey($companies_pkey, $users_pkey, $companies_departments_pkey);
}

sub load_companies_departments_pkey($self, $companies_pkey, $users_pkey, $companies_departments_pkey) {
    return $self->load_pk(
        $self->table_name, $self->fields(), $self->primary_key_name(), $companies_departments_pkey
    );
}

1;

