package Daje::Controller::Companies::Super::CompaniesCompaniesList;
use Mojo::Base 'Mojolicious::Controller', -base, -signatures;
use v5.42;

# NAME
# ====
#
# Daje::Controller::Companies::Super::CompaniesCompaniesList - Model class
#
# SYNOPSIS
# ========
#
#       use Daje::Controller::Companies::Super::vCompaniesCompanies##
#
# DESCRIPTION
# ===========
#
# Daje::Controller::Companies::Super::CompaniesCompanies is a standard controller
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#
# This file is generated automatically by Daje Tools 2026-04-06 14:13:01.
# It will be re-generated by Daje Tools again.
# <!-- Autogenerated file 2026-04-06 14:13:01 -->

our $VERSION = '0.01';

sub load_all_companies_companies($self) {
    $self->app->log->debug('Daje::Controller::Super::CompaniesCompaniesList::load_all_companies_companies ');
    $self->render_later;
    my ($companies_pkey, $users_pkey) = $self->jwt->companies_users_pkey(
         $self->req->headers->header('X-Token-Check')
    );

    $self->app->log->debug($self->req->headers->header('X-Token-Check'));

    $self->v_companies_companies_list->load_all_companies_companies_p($companies_pkey, $users_pkey)->then(sub($result) {
        $self->render(json => $result->{data});
    })->catch(sub($err) {
        $self->app->log->error('Daje::Controller::Super::CompaniesCompaniesList::load_all_companies_companies ' . $err);
        $self->render
    });
}
sub load_list_companies_workflow_fkey($self) {
    $self->app->log->debug('Daje::Controller::Super::CompaniesCompaniesList::load_listcompanies_workflow_fkey ');
    $self->render_later;
    my ($companies_pkey, $users_pkey) = $self->jwt->companies_users_pkey(
         $self->req->headers->header('X-Token-Check')
    );
    my $fkey = $self->param('companies_workflow_fkey');

    $self->app->log->debug($self->req->headers->header('X-Token-Check'));
    # my $setting = $self->param('setting');
    $self->v_companies__list->companies_workflow_fkey_p($companies_pkey, $users_pkey,$fkey)->then(sub($result) {
        $self->render(json => $result->{data});
    })->catch(sub($err) {
        $self->app->log->error('Daje::Controller::Super::CompaniesCompanies::load_companies_workflow_fkey ' . $err);
        $self->render
    });
}sub load_list_languages_lan_fkey($self) {
    $self->app->log->debug('Daje::Controller::Super::CompaniesCompaniesList::load_listlanguages_lan_fkey ');
    $self->render_later;
    my ($companies_pkey, $users_pkey) = $self->jwt->companies_users_pkey(
         $self->req->headers->header('X-Token-Check')
    );
    my $fkey = $self->param('languages_lan_fkey');

    $self->app->log->debug($self->req->headers->header('X-Token-Check'));
    # my $setting = $self->param('setting');
    $self->v_languages__list->languages_lan_fkey_p($companies_pkey, $users_pkey,$fkey)->then(sub($result) {
        $self->render(json => $result->{data});
    })->catch(sub($err) {
        $self->app->log->error('Daje::Controller::Super::CompaniesCompanies::load_languages_lan_fkey ' . $err);
        $self->render
    });
}
1;

