package Daje::Controller::Companies::Super::CompaniesDefaultsList;
use Mojo::Base 'Mojolicious::Controller', -base, -signatures;
use v5.42;

# NAME
# ====
#
# Daje::Controller::Companies::Super::CompaniesDefaultsList - Model class
#
# SYNOPSIS
# ========
#
#       use Daje::Controller::Companies::Super::vCompaniesDefaults##
#
# DESCRIPTION
# ===========
#
# Daje::Controller::Companies::Super::CompaniesDefaults is a standard controller
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#
# This file is generated automatically by Daje Tools 2026-04-06 14:13:01.
# It will be re-generated by Daje Tools again.
# <!-- Autogenerated file 2026-04-06 14:13:01 -->

our $VERSION = '0.01';

sub load_all_companies_defaults($self) {
    $self->app->log->debug('Daje::Controller::Super::CompaniesDefaultsList::load_all_companies_defaults ');
    $self->render_later;
    my ($companies_pkey, $users_pkey) = $self->jwt->companies_users_pkey(
         $self->req->headers->header('X-Token-Check')
    );

    $self->app->log->debug($self->req->headers->header('X-Token-Check'));

    $self->v_companies_defaults_list->load_all_companies_defaults_p($companies_pkey, $users_pkey)->then(sub($result) {
        $self->render(json => $result->{data});
    })->catch(sub($err) {
        $self->app->log->error('Daje::Controller::Super::CompaniesDefaultsList::load_all_companies_defaults ' . $err);
        $self->render
    });
}

1;

