package Daje::Controller::Companies::Super::CompaniesDepartmentsList;
use Mojo::Base 'Mojolicious::Controller', -base, -signatures;
use v5.42;

# NAME
# ====
#
# Daje::Controller::Companies::Super::CompaniesDepartmentsList - Model class
#
# SYNOPSIS
# ========
#
#       use Daje::Controller::Companies::Super::vCompaniesDepartments##
#
# DESCRIPTION
# ===========
#
# Daje::Controller::Companies::Super::CompaniesDepartments is a standard controller
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#
# This file is generated automatically by Daje Tools 2026-04-06 14:13:01.
# It will be re-generated by Daje Tools again.
# <!-- Autogenerated file 2026-04-06 14:13:01 -->

our $VERSION = '0.01';

sub load_all_companies_departments($self) {
    $self->app->log->debug('Daje::Controller::Super::CompaniesDepartmentsList::load_all_companies_departments ');
    $self->render_later;
    my ($companies_pkey, $users_pkey) = $self->jwt->companies_users_pkey(
         $self->req->headers->header('X-Token-Check')
    );

    $self->app->log->debug($self->req->headers->header('X-Token-Check'));

    $self->v_companies_departments_list->load_all_companies_departments_p($companies_pkey, $users_pkey)->then(sub($result) {
        $self->render(json => $result->{data});
    })->catch(sub($err) {
        $self->app->log->error('Daje::Controller::Super::CompaniesDepartmentsList::load_all_companies_departments ' . $err);
        $self->render
    });
}
sub load_list_companies_companies_fkey($self) {
    $self->app->log->debug('Daje::Controller::Super::CompaniesDepartmentsList::load_listcompanies_companies_fkey ');
    $self->render_later;
    my ($companies_pkey, $users_pkey) = $self->jwt->companies_users_pkey(
         $self->req->headers->header('X-Token-Check')
    );
    my $fkey = $self->param('companies_companies_fkey');

    $self->app->log->debug($self->req->headers->header('X-Token-Check'));
    # my $setting = $self->param('setting');
    $self->v_companies__list->companies_companies_fkey_p($companies_pkey, $users_pkey,$fkey)->then(sub($result) {
        $self->render(json => $result->{data});
    })->catch(sub($err) {
        $self->app->log->error('Daje::Controller::Super::CompaniesDepartments::load_companies_companies_fkey ' . $err);
        $self->render
    });
}
1;

