package Daje::Controller::Companies::Super::CompaniesCompaniesList;
use Mojo::Base 'Mojolicious::Controller', -base, -signatures;
use v5.42;

# NAME
# ====
#
# Daje::Controller::Companies::Super::CompaniesCompaniesList - Model class
#
# SYNOPSIS
# ========
#
#       use Daje::Controller::Companies::Super::vCompaniesCompanies##
#
# DESCRIPTION
# ===========
#
# Daje::Controller::Companies::Super::CompaniesCompanies is a standard controller
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#
# This file is generated automatically by Daje Tools 2026-01-18 17:25:44.
# It will be re-generated by Daje Tools again.
# <!-- Autogenerated file 2026-01-18 17:25:44 -->

our $VERSION = '0.01';

sub load_all_companies_companies($self) {
    $self->app->log->debug('Daje::Controller::Super::CompaniesCompaniesList::load_all_companies_companies ');
    $self->render_later;
    my ($companies_pkey, $users_pkey) = $self->jwt->companies_users_pkey(
         $self->req->headers->header('X-Token-Check')
    );

    $self->app->log->debug($self->req->headers->header('X-Token-Check'));
    # my $setting = $self->param('setting');
    $self->v_companies_companies_list->load_all_companies_companies_p()->then(sub($result) {
        $self->render(json => $result->{data});
    })->catch(sub($err) {
        $self->app->log->error('Daje::Controller::Super::CompaniesCompaniesList::load_all_companies_companies ' . $err);
        $self->render
    });
}

1;

