package Daje::Controller::Companies::Super::CompaniesRoles;
use Mojo::Base 'Mojolicious::Controller', -base, -signatures;
use v5.42;

# NAME
# ====
#
# Daje::Controller::Super::Companies::CompaniesRoles - Model class
#
# SYNOPSIS
# ========
#
#       use Daje::Controller::Companies::Super::vCompaniesRoles##
#
# DESCRIPTION
# ===========
#
# Daje::Controller::Companies::Super::CompaniesRoles is a standard controller
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#
# This file is generated automatically by Daje Tools 2026-02-13 14:55:23.
# It will be re-generated by Daje Tools again.
# <!-- Autogenerated file 2026-02-13 14:55:23 -->

our $VERSION = '0.01';

sub load_companies_roles_pkey($self) {
    $self->app->log->debug('Daje::Controller::Super::CompaniesRoles::load_companies__fkey ');
    $self->render_later;
    my ($companies_pkey, $users_pkey) = $self->jwt->companies_users_pkey(
         $self->req->headers->header('X-Token-Check')
    );
    my $pkey = $self->param('companies_roles_pkey');

    $self->app->log->debug($self->req->headers->header('X-Token-Check'));
    # my $setting = $self->param('setting');
    $self->v_companies_roles->load_companies_roles_pkey_p($pkey)->then(sub($result) {
        $self->render(json => $result->{data});
    })->catch(sub($err) {
        $self->app->log->error('Daje::Controller::Super::CompaniesRoles::load_companies_roles_pkey ' . $err);
        $self->render
    });
}
sub load_companies_companies_fkey($self) {
    $self->app->log->debug('Daje::Controller::Super::CompaniesRoles::load_companies_companies_fkey ');
    $self->render_later;
    my ($companies_pkey, $users_pkey) = $self->jwt->companies_users_pkey(
         $self->req->headers->header('X-Token-Check')
    );
    my $fkey = $self->param('companies_companies_fkey');

    $self->app->log->debug($self->req->headers->header('X-Token-Check'));
    # my $setting = $self->param('setting');
    $self->v_companies_->companies_companies_fkey_p($fkey)->then(sub($result) {
        $self->render(json => $result->{data});
    })->catch(sub($err) {
        $self->app->log->error('Daje::Controller::Super::CompaniesRoles::load_companies_companies_fkey ' . $err);
        $self->render
    });
}sub load_authorities_role_fkey($self) {
    $self->app->log->debug('Daje::Controller::Super::CompaniesRoles::load_authorities_role_fkey ');
    $self->render_later;
    my ($companies_pkey, $users_pkey) = $self->jwt->companies_users_pkey(
         $self->req->headers->header('X-Token-Check')
    );
    my $fkey = $self->param('authorities_role_fkey');

    $self->app->log->debug($self->req->headers->header('X-Token-Check'));
    # my $setting = $self->param('setting');
    $self->v_authorities_->authorities_role_fkey_p($fkey)->then(sub($result) {
        $self->render(json => $result->{data});
    })->catch(sub($err) {
        $self->app->log->error('Daje::Controller::Super::CompaniesRoles::load_authorities_role_fkey ' . $err);
        $self->render
    });
}
1;

