package Daje::Workflow::Activities::Companies::Department;
use Mojo::Base 'Daje::Workflow::Common::Activity::Base', -base, -signatures;
use v5.42;

# NAME
# ====
#
# Daje::Workflow::Activities::Companies::Department - A workflow activity
#
# SYNOPSIS
# ========
#;
#
# DESCRIPTION
# ===========
#
# Daje::Workflow::Activities::Companies::Department is a Daje workflow activity.
#
# METHODS
# =======
#
# Daje::Workflow::Activities::Companies::Department inherits all methods from
# Daje::Workflow::Activities::Tools::Generate::Base and implements the following new ones.
#
# activity
#
# SEE ALSO
# ========
#
# Mojolicious, Mojolicious::Guides, https://mojolicious.org.
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated once automatically by Daje Tools 2026-02-02 15:02:14.
# It will not be touched by Daje Tools again.

# <!-- Autogenerated file 2026-02-02 15:02:14 -->


use Daje::Database::View::vCompaniesDefaults;
use Daje::Database::Model::CompaniesDepartments;
use Data::Dumper;

sub save_default_departments($self) {

    $self->model->insert_history(
        "Default departments",
        "Daje::Workflow::Activities::Companies::Department::save_default_departments",
        1
    );

    my $companies_fkey = $self->context->{context}->{companies_fkey};
    try {
        my $departments = Daje::Database::View::vCompaniesDefaults->new(
            db => $self->db
        )->load_companies_defaults_list(
            {
                category => 'department'
            }
        )->{data};

        my $length = scalar @{$departments};
        for (my $i = 0; $i < $length; $i++) {
            my $data = {
                name                     => @{$departments}[$i]->{value},
                code                     => @{$departments}[$i]->{key},
                companies_companies_fkey => $companies_fkey,
            };

            Daje::Database::Model::CompaniesDepartments->new(
                db => $self->db
            )->insert(
                $data
            );
        };
    } catch ($e) {
        $self->error->add_error($e)
    }

}
1;