package Daje::Controller::Companies::CompaniesDefaultsList;
use Mojo::Base 'Daje::Controller::Companies::Super::CompaniesDefaultsList', -base, -signatures;
use v5.42;

# NAME
# ====
#
# Daje::Controller::CompaniesDefaultsList - Model class
#
# SYNOPSIS
# ========
#
#       use Daje::Controller::Companies::CompaniesDefaultsList;
#
#
#
# DESCRIPTION
# ===========
#
# Daje::Controller::Companies::vCompaniesDefaultsList is a standard controller
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated automatically by Daje Tools 2026-04-06 10:24:38.
# It will not be re-generated by Daje Tools again.
# <!-- Autogenerated file 2026-04-06 10:24:38 -->

our $VERSION = '0.01';

1;

