package Daje::Controller::Companies::CompaniesDepartments;
use Mojo::Base 'Daje::Controller::Companies::Super::CompaniesDepartments', -base, -signatures;
use v5.42;

# NAME
# ====
#
# Daje::Controller::Companies::CompaniesDepartments - Controller class
#
# SYNOPSIS
# ========
#
#       use Daje::Controller::Companies::CompaniesDepartments
#
#
#
# DESCRIPTION
# ===========
#
# Daje::Controller::Companies::CompaniesDepartments is a standard controller
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated automatically by Daje Tools 2026-04-04 12:57:50.
# It will not be re-generated by Daje Tools again.
# <!-- Autogenerated file 2026-04-04 12:57:50 -->

our $VERSION = '0.01';

1;

