package Daje::Database::View::vCompaniesUsersList;
use Mojo::Base 'Daje::Database::View::Super::vCompaniesUsersList', -base, -async_await, -signatures;
use v5.42;

# NAME
# ====
#
# Daje::Database::View::vCompaniesUsersList - View class
#
# SYNOPSIS
# ========
#
#       use Daje::Database::View::vCompaniesUsersList;
#
#       my $class = Daje::Database::View::vCompaniesUsersList->new(db => $db);
#
# DESCRIPTION
# ===========
#
# Daje::Database::View::vCompaniesUsersList is the List View
#
# class that's only generated once. It inherits all
#
# methods from Daje::Database::View::Super::vCompaniesUsersList
#
# This class is meant for non standard methods.
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated once automatically by Daje Tools 2026-02-02 15:02:14.
# It will not be touched by Daje Tools again.
# <!-- Autogenerated file 2026-02-02 15:02:14 -->


our $VERSION = '0.01';


sub load_users_users_list_of_companies($self, $users_users_fkey) {

    return $self->load_users_users_list({users_users_fkey => $users_users_fkey});
}

1;

