package Daje::Database::View::vCompaniesDefaults;
use Mojo::Base 'Daje::Database::View::Super::vCompaniesDefaults', -base, -async_await, -signatures;
use v5.42;

# NAME
# ====
#
# Daje::Database::View::vCompaniesDefaults - View class
#
# SYNOPSIS
# ========
#
#       use Daje::Database::View::vCompaniesDefaults;
#
#       my $class = Daje::Database::View::vCompaniesDefaults->new(db => $db);
#
# DESCRIPTION
# ===========
#
# Daje::Database::View::vCompaniesDefaults is the View
#
# class that's only generated once. It inherits all
#
# methods from Daje::Database::View::Super::vCompaniesDefaults#
# This class is meant for non standard methods.
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated once automatically by Daje Tools 2026-04-06 14:13:00.
# It will not be touched by Daje Tools again.
# <!-- Autogenerated file 2026-04-06 14:13:00 -->


our $VERSION = '0.01';


sub load_companies_defaults_list($self, $key_value) {
    return $self->load_a_list(
        $self->table_name, $self->fields(), $key_value
    );
}

1;

