package Daje::Database::View::vCompaniesRolesList;
use Mojo::Base 'Daje::Database::View::Super::vCompaniesRolesList', -base, -async_await, -signatures;
use v5.42;

# NAME
# ====
#
# Daje::Database::View::vCompaniesRolesList - View class
#
# SYNOPSIS
# ========
#
#       use Daje::Database::View::vCompaniesRolesList;
#
#       my $class = Daje::Database::View::vCompaniesRolesList->new(db => $db);
#
# DESCRIPTION
# ===========
#
# Daje::Database::View::vCompaniesRolesList is the List View
#
# class that's only generated once. It inherits all
#
# methods from Daje::Database::View::Super::vCompaniesRolesList
#
# This class is meant for non standard methods.
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated once automatically by Daje Tools 2026-02-13 14:55:23.
# It will not be touched by Daje Tools again.
# <!-- Autogenerated file 2026-02-13 14:55:23 -->


our $VERSION = '0.01';

1;

