package Daje::Plugin::Companies::Routes;
use Mojo::Base -base, -signatures;
use v5.42;

# NAME
# ====
#
# Daje::Plugin::Companies::Routes - Model class
#
# SYNOPSIS
# ========
#
#       use Daje::Plugin::Companies::Routes;
#
#       my $class = Daje::Plugin::Companies::Routes->new();
#       $r->get('/companies/api/v1/companies/:companies_companies_pkey');#
#
# DESCRIPTION
# ===========
#
# Daje::Plugin::Companies::Routes is the standard routes
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated automatically by Daje Tools 2026-01-18 17:25:43.
# It will be generated by Daje Tools again.
# <!-- Autogenerated file 2026-01-18 17:25:43 -->

our $VERSION = '0.01';

sub routes($self, $app, $config) {
    my $r = $app->routes;
    $r->get('/companies/api/v1/companies/:companies_companies_pkey')->to('CompaniesCompanies#companies_companies_pkey');

    $r->get('/companies/api/v1/companies_list_all/')->to('CompaniesCompaniesList#load_all_companies_companies');
}

